# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("LGT", "S2GT", "SGT", "ets", "etsAAM", "noglobal", "noglobalSGT", "nohet", "nohetSGT", "nostudent", "nostudentSGT")

# load each stan module
Rcpp::loadModule("stan_fit4LGT_mod", what = TRUE)
Rcpp::loadModule("stan_fit4S2GT_mod", what = TRUE)
Rcpp::loadModule("stan_fit4SGT_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ets_mod", what = TRUE)
Rcpp::loadModule("stan_fit4etsAAM_mod", what = TRUE)
Rcpp::loadModule("stan_fit4noglobal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4noglobalSGT_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nohet_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nohetSGT_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nostudent_mod", what = TRUE)
Rcpp::loadModule("stan_fit4nostudentSGT_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
